ALTER TABLE cart_items DROP CONSTRAINT IF EXISTS cart_items_pkey;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
UPDATE cart_items SET id = DEFAULT WHERE id IS NULL;
ALTER TABLE cart_items ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'pk_cart_items_id'
    ) THEN
        ALTER TABLE cart_items
            ADD CONSTRAINT pk_cart_items_id PRIMARY KEY (id);
    END IF;
END $$;

ALTER TABLE user_order_items DROP CONSTRAINT IF EXISTS user_order_items_pkey;
ALTER TABLE user_order_items ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
UPDATE user_order_items SET id = DEFAULT WHERE id IS NULL;
ALTER TABLE user_order_items ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'pk_user_order_items_id'
    ) THEN
        ALTER TABLE user_order_items
            ADD CONSTRAINT pk_user_order_items_id PRIMARY KEY (id);
    END IF;
END $$;
