FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
ARG SERVICE_PATH
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY ./$SERVICE_PATH/package.json ./
RUN npm install -f


# Rebuild the source code only when needed
FROM base AS builder

ARG NEXT_PRIVATE_LOCAL_WEBPACK
ENV NEXT_PRIVATE_LOCAL_WEBPACK $NEXT_PRIVATE_LOCAL_WEBPACK
ARG NEXT_PUBLIC_JIRA_DOMAIN
ENV NEXT_PUBLIC_JIRA_DOMAIN $NEXT_PUBLIC_JIRA_DOMAIN
ARG NEXT_PUBLIC_JIRA_API_TOKEN
ENV NEXT_PUBLIC_JIRA_API_TOKEN $NEXT_PUBLIC_JIRA_API_TOKEN
ARG NEXT_PUBLIC_JIRA_PROJECT_KEY
ENV NEXT_PUBLIC_JIRA_PROJECT_KEY $NEXT_PUBLIC_JIRA_PROJECT_KEY
ARG NEXT_PUBLIC_JIRA_EMAIL
ENV NEXT_PUBLIC_JIRA_EMAIL $NEXT_PUBLIC_JIRA_EMAIL

ARG SERVICE_PATH
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./$SERVICE_PATH/. .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN \
  if [ -f package.json ]; then npm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Production image, copy all the files and run next
FROM base AS runner
ARG SERVICE_PORT
ARG NEXT_PRIVATE_LOCAL_WEBPACK
ENV NEXT_PRIVATE_LOCAL_WEBPACK $NEXT_PRIVATE_LOCAL_WEBPACK
ARG NEXT_PUBLIC_JIRA_DOMAIN
ENV NEXT_PUBLIC_JIRA_DOMAIN $NEXT_PUBLIC_JIRA_DOMAIN
ARG NEXT_PUBLIC_JIRA_API_TOKEN
ENV NEXT_PUBLIC_JIRA_API_TOKEN $NEXT_PUBLIC_JIRA_API_TOKEN

WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public* ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY ./$SERVICE_PATH/*.* ./

USER nextjs

EXPOSE $SERVICE_PORT

ENV PORT $SERVICE_PORT

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js