/* eslint-disable */
// Generated by scripts/contracts/openapi_contracts.py
// Shared types used by all generated API clients.

export type RequestQueryValue = string | number | boolean | null | undefined;
export type RequestQuery = Record<string, RequestQueryValue | RequestQueryValue[]>;

export interface OperationRequestOptions {
  pathParams?: Record<string, string | number>;
  query?: RequestQuery;
  body?: unknown;
  headers?: HeadersInit;
  credentials?: RequestCredentials;
  signal?: AbortSignal;
}

export class ContractApiError extends Error {
  constructor(
    message: string,
    public readonly operationId: string,
    public readonly method: string,
    public readonly path: string,
    public readonly statusCode: number,
    public readonly responseBody?: string
  ) {
    super(message);
    this.name = "ContractApiError";
  }

  get status(): number {
    return this.statusCode;
  }
}
