/* eslint-disable */
// Generated by scripts/contracts/openapi_contracts.py from contracts/openapi/manifest.json

export const CONTRACT_SNAPSHOT_MANIFEST = {
  "schemaVersion": 1,
  "services": {
    "cloudapp": {
      "owner": "cloudapp",
      "releaseCritical": true,
      "snapshotRevision": 1,
      "sourceTitle": "Cloudapp API",
      "upstreamVersion": "v0.01"
    },
    "petstore": {
      "owner": "petstore",
      "releaseCritical": false,
      "snapshotRevision": 1,
      "sourceTitle": "Petstore API",
      "upstreamVersion": "v1"
    },
    "vehicles": {
      "owner": "vehicles-api",
      "releaseCritical": false,
      "snapshotRevision": 1,
      "sourceTitle": "Vehicle REST API",
      "upstreamVersion": "v1.0"
    }
  }
} as const;

export type ContractManifest = typeof CONTRACT_SNAPSHOT_MANIFEST;
export type ContractServiceName = keyof ContractManifest["services"];
export type ContractServiceManifest = ContractManifest["services"][ContractServiceName];

export const CONTRACT_SNAPSHOT_REVISIONS = {
  "cloudapp": 1,
  "petstore": 1,
  "vehicles": 1
} as const;
export const CONTRACT_UPSTREAM_VERSIONS = {
  "cloudapp": "v0.01",
  "petstore": "v1",
  "vehicles": "v1.0"
} as const;
